version: 1
disable_existing_loggers: False

formatters:
  uvicorn:
    (): uvicorn.logging.DefaultFormatter
    fmt: "%(levelprefix)s %(asctime)s - %(name)s - %(message)s"
    use_colors: true
  default:
    (): colorlog.ColoredFormatter
    fmt: "%(asctime)s - %(log_color)s%(levelname)s%(reset)s - [%(threadName)s] - %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    # use_colors: True
  access:
    (): colorlog.ColoredFormatter
    fmt: "%(asctime)s - %(log_color)s%(levelname)s%(reset)s - [%(threadName)s] - %(name)s - %(message)s"
    # use_colors: True
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn.access:
    handlers:
    - access
    level: INFO
    propagate: False

  # # Uncomment to enable SQL debug logging
  # sql:
  #   handlers:
  #   - default
  #   level: DEBUG
  #   propagate: False

root:
  handlers:
  - default
  level: INFO
